---
title: "Simulation code and plot"
author: "Wanglab"
date: "2021.6.28"
output: rmarkdown::github_document
---

```{r ,message=FALSE,warning=FALSE}
library(parallel)
library(MetaCycle)
library(dplyr)
library(tidyr)
func_num = 1000
time_num = 24
gene_num = 10000
gene_len = 1002
cost_c_low = 1
cost_c_up = 10000
    
func_num_gene_low = 1
func_num_gene_up = 100
expr_func_gene_low = 10
expr_func_gene_up = 100
point_pcc = function(x,y,xlab='',ylab='',main='',textx=0,text1y=0,text2y=0,cex=1,...){
  plot(x,y,
       ...,
       xlab = xlab, ylab = ylab, main = main,
       pch = 20)
  text_pvalue = cor.test(x,y)$p.value %>% 
    round(digits = 3)
  text_cor = cor.test(x,y)$estimate %>% 
    round(digits = 3)
  text(textx,text1y,paste0('pcc p = ',text_pvalue),
       pos = 4, cex = cex,offset = 0)
  text(textx,text2y,paste0('pcc r = ',text_cor),
       pos = 4,cex = cex,offset = 0)
}
n_level_num = function(data,id,n=5){
  data_num = length(data)
  id_ordered = id[order(data)]
  id_group = round((data_num/n)*1:n)
  id_group_1 = c(0,id_group[-n])+1
  id_group_2 = id_group
  inlevel_num = 1:n
  for (i in 1:n) {
    inlevel_num[i] = sum(id_ordered[id_group_1[i]:id_group_2[i]])
  }
  return(inlevel_num)
}
single_parallel <- function(func,iterable,...,cores = 0,env_val = c(),packages = c()){

  library(parallel)
 
  if (cores != 0) {
    cl <- makeCluster(cores)
  }
  else{
    cores <- detectCores()
    cl <- makeCluster(cores)
  }

  clusterExport(cl,deparse(substitute(func)))
  clusterExport(cl,env_val)
  clusterExport(cl,'packages',envir = environment())
  clusterEvalQ(cl,{
    for (i in packages) {
      library(i,character.only = T)
    }
  })
  result <- parSapply(cl,iterable,func,...)

  stopCluster(cl)
  return(result)
}
```


```{r,warning=FALSE}
# cost of each gene
# gene length
gene_len_codon = rep(300,gene_num)
gene_len_codon %>% density() %>% plot(
  xlim = c(),
  xlab = 'gene length(codon number)',ylab = 'density',main = 'simulation')
```

```{r gene_func,collapse = T,warning=FALSE}
#gene codon
set.seed(1)
baseT=c('U','C','A','G')
codonT=c()
for(i in baseT){
  for(j in baseT){
    for(k in baseT){
      codonT=c(codonT,paste0(i,j,k))
    }
  }
}
CM_RNA = c(48.5,49.5,48.5,51.5)
names(CM_RNA) = c('A','C','G','U') 
sequence_list = rep('a',gene_num)
cost_c = rep(0,gene_num)
system.time(
  for (i in 1:gene_num) {
    tmp = sample((1:64)[-c(11,12,15)],gene_len_codon[i],replace = T)
    tmp = c(36,tmp)
    sequence_list[i] = codonT[tmp] %>% paste0(collapse = '')
    id_M = strsplit(sequence_list[i],'')[[1]]
    cost_c[i] = CM_RNA[id_M] %>% sum()
  })
```



```{r,include = F, eval=F,warning=FALSE}
# distribution of matrix_gene_func_bool in mouse
edge_go_dags = read.table("ContainedData/Simulation/edge_go_dags.txt",
                          stringsAsFactors = F)
vertex_go_dags = read.table("ContainedData/Simulation/vertex_go_dags.txt",
                            stringsAsFactors = F)
{
  mus_gomap = read.table("ContainedData/Simulation/mus_gomap.txt",
                         stringsAsFactors = F)
  mgi2ens = read.table("ContainedData/Simulation/MGI_to_ENSEMBL.txt",
                       header = T,sep = "\t",quote = "",stringsAsFactors = F)
  mgi2ens = mgi2ens[-2]
  names(mgi2ens)[c(1,2)] = c("ENSMUST_ID","MGI_ID")
  mgi2ens = mgi2ens[mgi2ens$MGI_ID!="No associated gene",]
  mgi2ens = mgi2ens[!duplicated(mgi2ens$MGI_ID),]
}
mgi_id_set = mus_gomap[,1] %>% unique()
{
  termseed = c("GO:0008150","GO:0003674","GO:0005575")
  termi = termseed
  termrank = matrix(0,nrow = nrow(vertex_go_dags),ncol = 20)
  rownames(termrank) = vertex_go_dags[,1]
  k=1
  while(length(termi)!=0){
    termrank[termi,k] = k
    indbool2 = edge_go_dags[,2] %in% termi
    termi = edge_go_dags[indbool2,1]
    k=k+1
  }
  termrank_l = apply(termrank,1,max)
  print(table(termrank_l))
  termrank_s = apply(termrank,1,function(x){min(x[x>0])})
  print(table(termrank_s))
}
f_gene_goterm_matrix = function(goclass='all',level_go='max number'){
  if (goclass =='all'){ 
    id =T}  else if(goclass=='BP'){ 
      id = vertex_go_dags[,2] =='P'}  else if(goclass=='CC'){ 
        id = vertex_go_dags[,2] =='C'}  else if(goclass=='MF'){
          id = vertex_go_dags[,2] =='F'}
  termrank_l_sub = termrank_l[id]
  table(termrank_l_sub) %>% print()
  if (level_go == 'max number') {level_go = table(termrank_l_sub) %>% which.max()}
  ind_tmp = termrank_l_sub==level_go
  termrank_l_sub_level = termrank_l_sub[ind_tmp] %>% names()
  gene_num_per_func = c()
  tmp_genelist = c()
  gene_term_list = c()
  for (i in 1:length(termrank_l_sub_level)) {
    # print(i)
    {
      termseed = termrank_l_sub_level[i]
      termi = termseed
      indbool1 = F
      while(length(termi)!=0){
        indbool2 = edge_go_dags[,2] %in% termi
        indbool1 = indbool1 | indbool2
        termi = edge_go_dags[indbool2,1]
      }
      termall = union(edge_go_dags[indbool1,1],termseed)
      mgi_id_set_termseed = unique(mus_gomap[mus_gomap[,3] %in% termall, 1])
      if (length(mgi_id_set_termseed)>0) {
        gene_term_list = rbind(gene_term_list, cbind(mgi_id_set_termseed,termseed))
      }
    }
    gene_num_per_func = c(gene_num_per_func,length(mgi_id_set_termseed))
    tmp_genelist = c(tmp_genelist,mgi_id_set_termseed)
  }
  tmp_hash = cbind(rep(termrank_l_sub_level,gene_num_per_func),tmp_genelist)
  table(termrank_l_sub) %>% print()
  gene_num_per_func = gene_num_per_func[gene_num_per_func>0]
  func_num_per_gene = tmp_hash[,2] %>% table()
  paste0('GO level: ',level_go,'\n') %>% cat()
  paste0('term number: ',length(gene_num_per_func),'\n') %>% cat()
  paste0('gene number: ',length(func_num_per_gene),'\n') %>% cat()
  gene_term_matrix = table(gene_term_list[,1], gene_term_list[,2]) %>% as.matrix()
  paste0('term number: ',ncol(gene_term_matrix),'\n') %>% cat()
  paste0('gene number: ',nrow(gene_term_matrix),'\n') %>% cat()
  return(gene_term_matrix)
}

matrix_gene_func_BoolMouse = f_gene_goterm_matrix(goclass = 'MF')
aam = which(matrix_gene_func_BoolMouse==1,arr.ind = T)
bbm = cbind(rowSums(matrix_gene_func_BoolMouse)[aam[,1]]
            ,colSums(matrix_gene_func_BoolMouse)[aam[,2]])

```



```{r,eval=T,include=T,fig.width=7,fig.height=7,warning=FALSE}
#distribution of matrix_gene_func_bool in 8 species
filename = c("ContainedData/EnergyCost/go_annotation_matrix/arabidopsis_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/chalm_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/cyanobacteria_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/fly_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/human_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/mouse_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/neurospora_go_anno.csv",
             "ContainedData/EnergyCost/go_annotation_matrix/yeast_go_anno.csv")
speciesname = strsplit(filename,split = '\\\\') %>% 
  lapply('[',6) %>% 
  unlist %>% 
  strsplit(split = '_') %>% 
  lapply('[',1) %>% 
  unlist
tmp_matrix = matrix(ncol = 4,nrow = 8)
colnames(tmp_matrix) = c('nrow','ncol','1','ratio')
rownames(tmp_matrix) = speciesname
par(mfrow = c(4,5))
for (i in 1:8) {
  tmp = read.csv(filename[i],header = T,row.names = 1)
  tmp_matrix[i,] = c(dim(tmp),
                     sum(as.vector(tmp)),
                     sum(as.vector(tmp))/(dim(tmp)[1]*dim(tmp)[2]))
  
  colSums(tmp) %>% table() %>% plot(log = 'x',main = speciesname[i])
  tmp1 = colSums(tmp) %>% table()
  plot(names(tmp1) %>% as.integer() %>% log(),tmp1 %>% log())
  
  rowSums(tmp) %>% table() %>% plot(log = 'x')
  tmp2 = rowSums(tmp) %>% table()
  plot(names(tmp2) %>% as.integer() %>% log(),tmp2 %>% log())
  plot(names(tmp2) %>% as.integer(),tmp2 %>% log())
}
print(tmp_matrix)
```


```{r,warning=FALSE}
# matrix_gene_func_bool
max_fnum = 50
slope_f = 0
prob_func_number = seq(from = slope_f,to = 1,by = (1-slope_f)/(max_fnum-1)) %>% rev()
set.seed(1)
vector_gene_FuncNum = sample(1:max_fnum,gene_num,replace = T,prob = prob_func_number)
sum(vector_gene_FuncNum)

max_gnum = 500
slope_g = 0
prob_gene_number = seq(from = slope_g,to = 1,by = (1-slope_g)/(max_gnum-1)) %>% rev()
set.seed(1)
vector_func_GeneNum = sample(1:max_gnum,func_num,replace = T,prob = prob_gene_number)
sum(vector_func_GeneNum)
```


```{r,warning=FALSE}
#distribution of vector_gene_FuncNum and vector_func_GeneNum
plot(table(vector_func_GeneNum),
     xlab = 'gene number',ylab = 'function number',main = 'density of gene number')
c_gene = table(vector_func_GeneNum)[1]/prob_gene_number[1]
lines(prob_gene_number*c_gene)
plot(table(vector_func_GeneNum),
     xlab = 'gene number',ylab = 'function number',main = 'density of gene number',
     log='x')
c_gene = table(vector_func_GeneNum)[1]
lines(prob_gene_number*c_gene)
plot(names( table(vector_func_GeneNum)) %>% as.integer() %>% log()
     ,table(vector_func_GeneNum) %>% log())
plot(density(vector_func_GeneNum))
#
plot(table(vector_gene_FuncNum),
     xlab = 'function number',ylab = 'gene number',main = 'density of function number',
     log='')
c_func = table(vector_gene_FuncNum)[1]/prob_func_number[1]
lines(prob_func_number*c_func)
plot(table(vector_gene_FuncNum),
     xlab = 'function number',ylab = 'gene number',main = 'density of function number',
     log='x')
c_func = table(vector_gene_FuncNum)[1]/prob_func_number[1]
lines(prob_func_number*c_func)
plot(density(vector_gene_FuncNum))
```

```{r,warning=FALSE}
vector_func_GeneNum %>% sort(decreasing = T) %>% head()
tmp = sum(vector_func_GeneNum) - sum(vector_gene_FuncNum)
tmp
```

```{r,warning=FALSE}
f_AdjNum = function(v1 = vector_func_GeneNum,v2 = vector_gene_FuncNum,vs){
  if (sum(v1)==sum(v2)) {
    return(v1)
  }else if(sum(v1)>sum(v2)){
    for (i in vs) {
      tmp_id = which(v1>i)
      tmp_id = sample(tmp_id,1)
      v1[tmp_id] = v1[tmp_id] - i
    }
    return(v1) 
  }else if(sum(v1)<sum(v2)){
    tmp_id = which(v1 == 1)
    tmp_id = sample(tmp_id,length(vs))
    v1[tmp_id] = v1[tmp_id] + vs
    return(v1) 
  }
}
vector_func_GeneNum = f_AdjNum(vs = c(200,198))
sum(vector_func_GeneNum)
sum(vector_gene_FuncNum)
length(vector_func_GeneNum)
length(vector_gene_FuncNum)
```


```{r,warning=FALSE}
matrix_gene_func_bool = matrix(0,nrow = gene_num,ncol = func_num)
vector_func_LoopGeneNum = vector_func_GeneNum
for (i in 1:gene_num) {
  func_id_loop = order(vector_func_LoopGeneNum,decreasing = T)[1:vector_gene_FuncNum[i]]
  matrix_gene_func_bool[i,func_id_loop] = 1
  vector_func_LoopGeneNum[func_id_loop] = vector_func_LoopGeneNum[func_id_loop]-1
}
```

```{r,warning=FALSE}
plot(table(colSums(matrix_gene_func_bool)),
     xlab = 'gene number',ylab = 'function number',main = 'density of gene number',
     log='x')
plot(names( table(colSums(matrix_gene_func_bool))) %>% as.integer() %>% log()
     ,table(colSums(matrix_gene_func_bool)) %>% log())
plot(density(vector_func_GeneNum))
#
plot(table(rowSums(matrix_gene_func_bool)),
     xlab = 'function number',ylab = 'gene number',main = 'density of function number',
     log='')
plot(density(vector_gene_FuncNum))
```



```{r,warning=FALSE}
# matrix_gene_func_expr
set.seed(1)
matrix_gene_func_expr = matrix(0,nrow = gene_num,ncol = func_num)
matrix_gene_func_expr[matrix_gene_func_bool==1] = 
  sample(10:100,sum(matrix_gene_func_bool),replace = T)
matrix_gene_func_expr[matrix_gene_func_expr>0] %>% density() %>% plot(
  xlab = 'expression level',ylab = 'density',
  main = 'density of expression for each gene each function'
)
```




```{r func_time,warning=FALSE}
# matrix_func_time
vector_func_TimeNum = sample(1:24,func_num,replace = T)
set.seed(1)
sample_prob = dnorm(seq(-2,2,by = 4/23))+0.5
```



```{r,warning=FALSE}
#calculate matrix_func_time_bool
tmp = c()
set.seed(1)
for (i in 1:func_num) {
  tmp = c(tmp,sample(1:24,vector_func_TimeNum[i],replace = F,prob = sample_prob))
}
plot(sample_prob,
     xlab = 'time point',ylab = 'probability to sample',main = 'probability of function activation',
     ylim =c(0,1),
     pch = 20)
list_func_time = cbind(rep(1:func_num,vector_func_TimeNum),tmp)
colnames(list_func_time) = c('func','time')
plot(table(vector_func_TimeNum),
     xlab = 'time number',ylab = 'function number',main = 'distribution of time number')
list_func_time[,2] %>% table() %>% plot(
  xlab = 'time point',ylab = 'function number', main = 'function number at each time point')
# list to matrix
matrix_func_time_bool = table(list_func_time[,1],list_func_time[,2]) %>% as.matrix()
matrix_func_time_bool %>% colSums() %>% summary()
matrix_func_time_bool %>% rowSums() %>% summary()
```


```{r,warning=FALSE}
matrix_func_time_bool = cbind(matrix_func_time_bool,matrix_func_time_bool,matrix_func_time_bool)
colnames(matrix_func_time_bool) = 1:72
```



```{r,warning=FALSE}
matrix_gene_time_FuncNum = (matrix_gene_func_expr != 0) %*% matrix_func_time_bool
matrix_gene_time_FuncNum %>% table() %>% 
  plot(xlab = 'function number', ylab = 'frequence', main = 'distribution from function number matrix')
```





```{r,warning=FALSE}
# matrix_gene_time
expr_need = matrix_gene_func_expr %*% matrix_func_time_bool
```



```{r}
expr_need %>% density() %>% 
  plot(xlab = 'function number', ylab = 'frequence', main = 'distribution from function number matrix')
```

```{r}
max_rand = 1.5
list_gene_MaxExpr = unlist(apply(expr_need, 1, max))*max_rand
expr_maxlimit = matrix(1,nrow = gene_num,ncol = 72) * list_gene_MaxExpr
```

```{r}
min_rand = 0.9
expr_minlimit = expr_need*min_rand
```


```{r}
expr_IncrementMaxFlex = expr_maxlimit - expr_minlimit
set.seed(1)
tmp = matrix(runif(gene_num*72),nrow = gene_num,ncol = 72)
expr_IncrementRandFlex = expr_IncrementMaxFlex * tmp
expr_rand = expr_minlimit + expr_IncrementRandFlex
```



```{r}
#calculate of cost
expr_IncrementRand = expr_rand - expr_need
cost_IncrementRand = expr_IncrementRand * cost_c
cost_IncrementRandAbs = abs(cost_IncrementRand)
cost_IncrementRandBool = sign(cost_IncrementRand)
```

```{r calculate for different select strength}
# f_cir_para = function(xx){
#   # calculateexpr_constrained
#   sele_strength = xx
#   cost_IncrementConsAbs = exp(log(1+cost_IncrementRandAbs)*(1 - sele_strength))-1 #再映射到expr上去
#   expr_IncrementCons = cost_IncrementConsAbs/cost_IncrementRandAbs * expr_IncrementRand
#   expr_constrained = expr_need + expr_IncrementCons
# 
#   # set.seed(1)
#   # expr_constrained = expr_constrained+runif(720000,min = 0,max = 1)
#   timelist = 1:72
#   expr_out = expr_constrained
#   write.csv(as.data.frame(expr_out), file = paste0("E:/circidian_algorithm/Select_strength_result/cycMouseHypoRNA",xx,".csv"), row.names=T)
#   metatest = meta2d(infile=paste0("E:/circidian_algorithm/Select_strength_result/cycMouseHypoRNA",xx,".csv"), filestyle="csv",
#                     outdir = 'E:/circidian_algorithm/Select_strength_result/',outputFile = F,
#                     minper = 20,maxper = 28,
#                     timepoints=timelist
#   )
#   return(sum(metatest$meta$meta2d_BH.Q<0.05))
# }
# sele_strength_seq = seq(0.01,0.2,by = 0.01)
# 
# 
# 
# res = single_parallel(func = f_cir_para
#                       ,iterable = sele_strength_seq
#                       ,env_val = c('cost_IncrementRandAbs','expr_IncrementRand','expr_need')
#                       ,packages = c('MetaCycle','dplyr'))
# 
# cbind(sele_strength_seq,res)
# plot(sele_strength_seq,res
#      ,xlab = 'sele_strength',ylab = 'circadian number')
```


```{r}
#select select strength
sele_strength = 0.05
cost_IncrementConsAbs = exp(log(1+cost_IncrementRandAbs)*(1 - sele_strength))-1 
expr_IncrementCons = cost_IncrementConsAbs/cost_IncrementRandAbs * expr_IncrementRand
expr_constrained = expr_need + expr_IncrementCons
```






```{r}
(expr_constrained - expr_need) %>% '<'(0) %>% sum()
(expr_constrained - expr_need) %>% '<'(0) %>% sum() %>% '/'(720000)
```



```{r}
#calculate cost_constrained
cost_constrained = expr_constrained * cost_c
```



```{r cir}
#final expression data
library(MetaCycle)
expr_out = expr_constrained
timelist = 1:72
write.csv(as.data.frame(expr_out), file = paste0("cycMouseHypoRNA",sele_strength,".csv"), row.names=T)
system.time({
  metatest = meta2d(infile=paste0("cycMouseHypoRNA",sele_strength,".csv"), filestyle="csv",
                    outdir = 'example',outputFile = F,
                    minper = 20,maxper = 28,
                    timepoints=timelist
  )
})
sum(metatest$meta$meta2d_BH.Q<0.05) %>% print()
```



```{r}
# observe features of simulation data
matrix_func_time_bool %>% as.vector() %>% length()
matrix_func_time_bool %>% as.vector() %>% '=='(0) %>% sum()
expr_need %>% as.vector() %>% length()
expr_need %>% as.vector() %>% '=='(0) %>% sum()
expr_constrained %>% as.vector() %>% length()
expr_constrained %>% as.vector() %>% '=='(0) %>% sum()
summary(expr_constrained %>% as.vector())
```


```{r}
id_cir = metatest$meta$meta2d_BH.Q<0.05
matrix_gene_func_BoolCir = matrix_gene_func_bool[id_cir,]
id_tmp = colSums(matrix_gene_func_BoolCir)!=0
matrix_gene_func_BoolCir = matrix_gene_func_BoolCir[,id_tmp]
```



```{r, include=T}
matrix_gene_func_bool %>% colSums() %>% table() %>%
  plot(log='x'
       ,xlab = 'gene numbers in one function',ylab = 'frequence')
text(70,300
     ,paste0('mean=',matrix_gene_func_bool %>% colSums() %>% mean() %>% round(digits = 2))
     ,cex = 1.2)
matrix_gene_func_BoolCir %>% colSums() %>% table() %>%
  plot(log='x'
       ,xlab = 'circadian gene numbers in one function',ylab = 'frequence')
text(40,150
     ,paste0('mean=',matrix_gene_func_BoolCir %>% colSums() %>% mean() %>% round(digits = 2))
     ,cex = 1.2)
matrix_gene_func_bool %>% rowSums() %>% table() %>%
  plot(log=''
       ,xlab = 'function numbers in one gene',ylab = 'frequence')
text(12,2500
     ,paste0('mean=',matrix_gene_func_bool %>% rowSums() %>% mean() %>% round(digits = 2))
     ,cex = 1.2)
matrix_gene_func_BoolCir %>% rowSums() %>% table() %>%
  plot(log=''
       ,xlab = 'function numbers in one circadian gene',ylab = 'frequence')
text(12,300
     ,paste0('mean=',matrix_gene_func_BoolCir %>% rowSums() %>% mean() %>% round(digits = 2))
     ,cex = 1.2)
```



```{r}
(matrix_gene_func_BoolCir %>% rowSums() %>% table() /
    (matrix_gene_func_bool %>% rowSums() %>% table())[rownames(
      matrix_gene_func_BoolCir %>% rowSums() %>% table())]) %>%
  plot(
    main = 'simulation',ylab = 'cir/all ratio',xlab = 'function number'
  )
tmp1 = (matrix_gene_func_bool[metatest$meta$meta2d_BH.Q<0.05,] %>% colSums())
tmp2 = matrix_gene_func_bool %>% colSums()
point_pcc(log10(tmp2[tmp1!=0]),log10(tmp1[tmp1!=0])
          ,main = 'simulation',ylab = 'log10(cir number)',xlab = 'log10(term size)'
          ,textx = 0.1,text1y = 2,text2y = 1.6)

tmp1 = (matrix_gene_func_bool[metatest$meta$meta2d_BH.Q<0.05,] %>% colSums()) /
  (matrix_gene_func_bool %>% colSums())
tmp2 = matrix_gene_func_bool %>% colSums()
point_pcc(log10(tmp2[tmp1!=0]),tmp1[tmp1!=0]
          ,xlab = 'log10(term size)',main = 'simulation',ylab = 'cir/all ratio'
          ,textx = 0,text1y = 0.2,text2y = 0.1)
cor.test(log10(tmp2[tmp1!=0]),tmp1[tmp1!=0])

id_tmp = sample(gene_num,sum(metatest$meta$meta2d_BH.Q<0.05))
tmp1 = (matrix_gene_func_bool[id_tmp,] %>% colSums())
tmp2 = matrix_gene_func_bool %>% colSums()
point_pcc(log10(tmp2[tmp1!=0]),log10(tmp1[tmp1!=0])
          ,main = 'simulation',ylab = 'log10(cir number)',xlab = 'log10(term size)'
          ,textx = 0.1,text1y = 2,text2y = 1.6)

tmp1 = (matrix_gene_func_bool[id_tmp,] %>% colSums()) /
  (matrix_gene_func_bool %>% colSums())
tmp2 = matrix_gene_func_bool %>% colSums()
point_pcc(log10(tmp2[tmp1!=0]),tmp1[tmp1!=0]
          ,xlab = 'log10(term size)',main = 'simulation',ylab = 'cir/all ratio'
          ,textx = 0,text1y = 0.2,text2y = 0.1)
cor.test(log10(tmp2[tmp1!=0]),tmp1[tmp1!=0])
```


```{r}
plot(colSums(matrix_func_time_bool),type = 'l')
id_cir = metatest$meta$meta2d_BH.Q<0.05
plot(metatest$meta$meta2d_Base,metatest$meta$meta2d_AMP,log = 'xy',
     xlab = 'log(expr)',ylab = 'log(amp)')
plot(metatest$meta$meta2d_Base[id_cir],metatest$meta$meta2d_AMP[id_cir],log = 'xy',
     xlab = 'log(expr)',ylab = 'log(amp)')
rowmean_cost = rowMeans(expr_constrained)
plot(metatest$meta$meta2d_Base[id_cir],rowmean_cost[id_cir],log = 'xy',
     xlab = 'log(expr)',ylab = 'log(cost)')
plot(n_level_num(data = rowMeans(expr_constrained),id = id_cir)
     ,type = 'l',
     ylab = 'circadian gene number')
tmp = n_level_num(apply(expr_constrained, 1, function(x){max(x) - min(x)}) %>% unlist,id = id_cir)
plot(tmp,type = 'l',ylab = 'circadian gene number')
```


